#!/usr/bin/env bash
# Download papers for ch08_rlhf
# Auto-generated by generate_download_scripts.py

set -euo pipefail

DEST="/Users/pranjal/Code/rl/ch08_rlhf/papers"
mkdir -p "$DEST"

# christiano:2017: 
[ -f "$DEST/christiano:2017.pdf" ] || curl -sL -o "$DEST/christiano:2017.pdf" "https://arxiv.org/pdf/1706.03741.pdf"
# Source: known_arxiv

# korbak2022rl: 
[ -f "$DEST/korbak2022rl.pdf" ] || curl -sL -o "$DEST/korbak2022rl.pdf" "https://arxiv.org/pdf/2210.01241.pdf"
# Source: known_arxiv

# mcfadden:1973: 
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# ouyang2022training: 
[ -f "$DEST/ouyang2022training.pdf" ] || curl -sL -o "$DEST/ouyang2022training.pdf" "https://arxiv.org/pdf/2203.02155.pdf"
# Source: known_arxiv

# rafailov2023direct: 
[ -f "$DEST/rafailov2023direct.pdf" ] || curl -sL -o "$DEST/rafailov2023direct.pdf" "https://arxiv.org/pdf/2305.18290.pdf"
# Source: known_arxiv

# stiennon2020learning: 
[ -f "$DEST/stiennon2020learning.pdf" ] || curl -sL -o "$DEST/stiennon2020learning.pdf" "https://arxiv.org/pdf/2009.01325.pdf"
# Source: known_arxiv

# yuan2024self: 
[ -f "$DEST/yuan2024self.pdf" ] || curl -sL -o "$DEST/yuan2024self.pdf" "https://arxiv.org/pdf/2401.10020.pdf"
# Source: known_arxiv

# ziegler2019fine: 
[ -f "$DEST/ziegler2019fine.pdf" ] || curl -sL -o "$DEST/ziegler2019fine.pdf" "https://arxiv.org/pdf/1909.08593.pdf"
# Source: known_arxiv

