#!/usr/bin/env bash
# Download papers for ch07_applications
# Auto-generated by generate_download_scripts.py

set -euo pipefail

DEST="/Users/pranjal/Code/rl/ch07_applications/papers"
mkdir -p "$DEST"

# ACA2011: The Patient Protection and Affordable Care Act
# Authors: Rosenbaum, Sara
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Alibaba2019: AliExpress Dynamic Pricing: A Learning Approach
# Authors: Wang, Yongfeng and Ouyang, Kangyi and Huang, Chunyan and Chen, Jian and Liu, Yan
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# ArnoldPorter2012: Antitrust Agencies Action in 2012
# Authors: Wilson Sonsini
[ -f "$DEST/Antitrust_Agencies_Action_in_2012.pdf" ] || curl -sL -o "$DEST/Antitrust_Agencies_Action_in_2012.pdf" "https://www.wsgr.com/a/web/229/pak-0312.pdf"
# Source: bib_url

# BakerBotts2020: The Hutchison Judgment
# Authors: Baker Botts
[ -f "$DEST/The_Hutchison_Judgment.pdf" ] || curl -sL -o "$DEST/The_Hutchison_Judgment.pdf" "https://www.bakerbotts.com/~/media/Files/Thought-Leadership/Publications/2020/December/The-Hutchinson.pdf"
# Source: bib_url

# Constancio2018: The New Area-Wide Model II: an extended version of the ECB's micro-founded model
# Authors: Coenen, Günter and Karadi, Peter and Schmidt, Sebastian and Warne, Anders
[ -f "$DEST/The_New_Area-Wide_Model_II_an_extended_version_of_the_ECBs_m.pdf" ] || curl -sL -o "$DEST/The_New_Area-Wide_Model_II_an_extended_version_of_the_ECBs_m.pdf" "https://www.ecb.europa.eu/pub/pdf/scpwps/ecb.wp2200.en.pdf"
# Source: bib_url

# DiDi2019: Reinforcement Learning for Order Dispatching: A Ride-Sharing Perspective
# Authors: Wang, Zhaodong and Qin, Zhiwei and Tang, Xiaocheng and Ye, Jieping and Zhu, Hong
[ -f "$DEST/Reinforcement_Learning_for_Order_Dispatching_A_Ride-Sharing.pdf" ] || curl -sL -o "$DEST/Reinforcement_Learning_for_Order_Dispatching_A_Ride-Sharing.pdf" "https://arxiv.org/pdf/1905.11566.pdf"
# Source: known_arxiv

# DLAPiper2020: Commission decision to prohibit Hutchison 3G UK/Telefonica UK merger annulled (G
# Authors: {Practical Law Competition}
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# FCC2020: Auction 97: Advanced Wireless Services (AWS-3)
# Authors: {Federal Communications Commission}
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Fischer2017: I'd rather have Bob Solow than an econometric model, but...
# Authors: Fischer, Stanley
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Google2018: Data center cooling using model-predictive control
# Authors: Gao, Jim
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# JPMorgan2018: J.P. Morgan's massive guide to machine learning and big data in the financial se
# Authors: Patel, Marko
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Liu2022: Dynamic Coupon Targeting Using Batch Deep Reinforcement Learning: An Application
# Authors: Liu, Xiao and Qin, Zhengling and Gao, Xiaoying and Huang, Junming
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Microsoft2022: Reinforcement Learning for Xbox Live Content Recommendations
# Authors: Ie, Eugene and Jain, Vihan and Wang, Jing and Narvekar, Sanmit and Agarwal, Rite
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Misra2019: Dynamic Online Pricing with Incomplete Information Using Multiarmed Bandit Exper
# Authors: Misra, Kanishka and Schwartz, Eric M. and Abernethy, Jacob
[ -f "$DEST/Dynamic_Online_Pricing_with_Incomplete_Information_Using_Mul.pdf" ] || curl -sL -o "$DEST/Dynamic_Online_Pricing_with_Incomplete_Information_Using_Mul.pdf" "https://arxiv.org/pdf/1902.04229.pdf"
# Source: known_arxiv

# NPR2025: 21 states are getting minimum wage bumps in 2025
# Authors: {NPR}
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# TCJA2018: Tax Cuts and Jobs Act
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

