#!/usr/bin/env bash
# Download papers for ch04_inverse_rl
# Auto-generated by generate_download_scripts.py

set -euo pipefail

DEST="/Users/pranjal/Code/rl/ch04_inverse_rl/papers"
mkdir -p "$DEST"

# Abbeel2004: Apprenticeship Learning via Inverse Reinforcement Learning
# Authors: Abbeel, Pieter and Ng, Andrew Y.
[ -f "$DEST/Apprenticeship_Learning_via_Inverse_Reinforcement_Learning.pdf" ] || curl -sL -o "$DEST/Apprenticeship_Learning_via_Inverse_Reinforcement_Learning.pdf" "https://arxiv.org/pdf/cs/0409043.pdf"
# Source: known_arxiv

# Bogota2015: Prediction of Refugee Migration Patterns Using Maximum Entropy Inverse Reinforce
# Authors: Bogota, Nicolás and Huang, Xiaocheng and Jebara, Tony
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Boularias2011: Relative Entropy Inverse Reinforcement Learning
# Authors: Boularias, Abdeslam and Kober, Jens and Peters, Jan
[ -f "$DEST/Relative_Entropy_Inverse_Reinforcement_Learning.pdf" ] || curl -sL -o "$DEST/Relative_Entropy_Inverse_Reinforcement_Learning.pdf" "https://arxiv.org/pdf/1506.07023.pdf"
# Source: known_arxiv

# Bronner2023: Detecting Anomalous Ride-Hailing Driver Routes using Inverse Reinforcement Learn
# Authors: Bronner, Yoav and Fishman, Amir and Ritov, Ya'acov and Shimshoni, Ilan
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# cao2021irl: Identifiability in inverse reinforcement learning
# Authors: Cao, Haoyang and Cohen, Samuel N. and Szpruch, Lukasz
[ -f "$DEST/Identifiability_in_inverse_reinforcement_learning.pdf" ] || curl -sL -o "$DEST/Identifiability_in_inverse_reinforcement_learning.pdf" "https://arxiv.org/pdf/2106.03788.pdf"
# Source: known_arxiv

# Chan2019: Selection with Variation in Diagnostic Skill: Evidence from Radiologists
# Authors: Chan, David C. and Gentzkow, Matthew and Yu, Chuan
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Ermon2015: Learning Large-Scale Dynamic Discrete Choice Models of Spatio-Temporal Preferenc
# Authors: Ermon, Stefano and Xue, Yexiang and Toth, Russell and Dilkina, Bistra and Bernst
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Finn2016: Guided Cost Learning: Deep Inverse Optimal Control via Policy Optimization
# Authors: Finn, Chelsea and Levine, Sergey and Abbeel, Pieter
[ -f "$DEST/Guided_Cost_Learning_Deep_Inverse_Optimal_Control_via_Policy.pdf" ] || curl -sL -o "$DEST/Guided_Cost_Learning_Deep_Inverse_Optimal_Control_via_Policy.pdf" "https://arxiv.org/pdf/1603.00448.pdf"
# Source: known_arxiv

# Fu2018: Learning Robust Rewards with Adversarial Inverse Reinforcement Learning
# Authors: Fu, Justin and Luo, Katie and Levine, Sergey
[ -f "$DEST/Learning_Robust_Rewards_with_Adversarial_Inverse_Reinforceme.pdf" ] || curl -sL -o "$DEST/Learning_Robust_Rewards_with_Adversarial_Inverse_Reinforceme.pdf" "https://arxiv.org/pdf/1710.11248.pdf"
# Source: known_arxiv

# Ho2016: Generative Adversarial Imitation Learning
# Authors: Ho, Jonathan and Ermon, Stefano
[ -f "$DEST/Generative_Adversarial_Imitation_Learning.pdf" ] || curl -sL -o "$DEST/Generative_Adversarial_Imitation_Learning.pdf" "https://arxiv.org/pdf/1606.03476.pdf"
# Source: known_arxiv

# kim2021irl: Reward Identification in Inverse Reinforcement Learning
# Authors: Kim, Kuno and Shiragur, Kirankumar and Garg, Shivam and Ermon, Stefano
[ -f "$DEST/Reward_Identification_in_Inverse_Reinforcement_Learning.pdf" ] || curl -sL -o "$DEST/Reward_Identification_in_Inverse_Reinforcement_Learning.pdf" "https://arxiv.org/pdf/2106.03788.pdf"
# Source: known_arxiv

# Kostrikov2018: Discriminator-Actor-Critic: Addressing Sample Inefficiency and Reward Bias in Ad
# Authors: Kostrikov, Ilya and Agrawal, Kumar Krishna and Dwibedi, Debidatta and Levine, Se
[ -f "$DEST/Discriminator-Actor-Critic_Addressing_Sample_Inefficiency_an.pdf" ] || curl -sL -o "$DEST/Discriminator-Actor-Critic_Addressing_Sample_Inefficiency_an.pdf" "https://arxiv.org/pdf/1809.02925.pdf"
# Source: known_arxiv

# Mai2015: A Nested Recursive Logit Model for Route Choice Analysis
# Authors: Mai, Tien and Fosgerau, Mogens and Frejinger, Emma
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# NgRussell2000: Algorithms for Inverse Reinforcement Learning
# Authors: Ng, Andrew Y. and Russell, Stuart J.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# OBriant2024: Inverse Reinforcement Learning for Structural Models
# Authors: O'Briant, Jackson B.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Ramachandran2007: Bayesian Inverse Reinforcement Learning
# Authors: Ramachandran, Deepak and Amir, Eyal
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Ratliff2006: Maximum Margin Planning
# Authors: Ratliff, Nathan D. and Bagnell, J. Andrew and Zinkevich, Martin A.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# rolland2022: Identifiability of rewards in inverse reinforcement learning
# Authors: Rolland, Hadrien and Pirotta, Matteo and Flet-Berliac, Yannis and Preux, Philipp
[ -f "$DEST/Identifiability_of_rewards_in_inverse_reinforcement_learning.pdf" ] || curl -sL -o "$DEST/Identifiability_of_rewards_in_inverse_reinforcement_learning.pdf" "https://arxiv.org/pdf/2202.09529.pdf"
# Source: known_arxiv

# rolland2022_identifiability: Identifiability of rewards in inverse reinforcement learning
# Authors: Rolland, Hadrien and Pirotta, Matteo and Flet-Berliac, Yannis and Preux, Philipp
[ -f "$DEST/Identifiability_of_rewards_in_inverse_reinforcement_learning.pdf" ] || curl -sL -o "$DEST/Identifiability_of_rewards_in_inverse_reinforcement_learning.pdf" "https://arxiv.org/pdf/2202.09529.pdf"
# Source: bib_arxiv

# Rust1987: Optimal Replacement of GMC Bus Engines: An Empirical Model of Harold Zurcher
# Authors: Rust, John
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Sharma2018: Directed-Info GAIL: Learning Hierarchical Policies from Unsegmented Demonstratio
# Authors: Sharma, Mohit and Sharma, Arjun and Rhinehart, Nicholas and Kitani, Kris M.
[ -f "$DEST/Directed-Info_GAIL_Learning_Hierarchical_Policies_from_Unseg.pdf" ] || curl -sL -o "$DEST/Directed-Info_GAIL_Learning_Hierarchical_Policies_from_Unseg.pdf" "https://arxiv.org/pdf/1805.07687.pdf"
# Source: known_arxiv

# shehab2024: Identifiability in Inverse Reinforcement Learning
# Authors: Shehab, Moussa and Sinha, Arunesh and Taylor, Matthew E.
[ -f "$DEST/Identifiability_in_Inverse_Reinforcement_Learning.pdf" ] || curl -sL -o "$DEST/Identifiability_in_Inverse_Reinforcement_Learning.pdf" "https://arxiv.org/pdf/2401.03608.pdf"
# Source: known_arxiv

# Wulfmeier2015: Maximum Entropy Deep Inverse Reinforcement Learning
# Authors: Wulfmeier, Markus and Ondruska, Peter and Posner, Ingmar
[ -f "$DEST/Maximum_Entropy_Deep_Inverse_Reinforcement_Learning.pdf" ] || curl -sL -o "$DEST/Maximum_Entropy_Deep_Inverse_Reinforcement_Learning.pdf" "https://arxiv.org/pdf/1507.04888.pdf"
# Source: known_arxiv

# Yancey2022: Inverse Reinforcement Learning for Labor Market Dynamics
# Authors: Yancey, Will and Bai, Haotian and Hanna, Rema
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Zeng2022: A Fully Single Loop Algorithm for Bilevel Optimization without Hessian Inverse
# Authors: Zeng, Jiawei and Gu, Bin and Huang, Heng
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Ziebart2008: Maximum Entropy Inverse Reinforcement Learning
# Authors: Ziebart, Brian D. and Maas, Andrew and Bagnell, J. Andrew and Dey, Anind K.
[ -f "$DEST/Maximum_Entropy_Inverse_Reinforcement_Learning.pdf" ] || curl -sL -o "$DEST/Maximum_Entropy_Inverse_Reinforcement_Learning.pdf" "https://arxiv.org/pdf/0710.4922.pdf"
# Source: known_arxiv

