#!/usr/bin/env bash
# Download papers for ch02_planning_learning
# Auto-generated by generate_download_scripts.py

set -euo pipefail

DEST="/Users/pranjal/Code/rl/ch02_planning_learning/papers"
mkdir -p "$DEST"

# agarwal2020: An Optimistic Perspective on Offline Reinforcement Learning
# Authors: Agarwal, Rishabh and Schuurmans, Dale and Norouzi, Mohammad
[ -f "$DEST/An_Optimistic_Perspective_on_Offline_Reinforcement_Learning.pdf" ] || curl -sL -o "$DEST/An_Optimistic_Perspective_on_Offline_Reinforcement_Learning.pdf" "https://arxiv.org/pdf/1907.04543.pdf"
# Source: known_arxiv

# agarwal2021theory: On the Theory of Policy Gradient Methods: Optimality, Approximation, and Distrib
# Authors: Agarwal, Alekh and Kakade, Sham M. and Lee, Jason D. and Mahajan, Gaurav
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# ayoub2020value: Model-Based Reinforcement Learning with Value-Targeted Regression
# Authors: Ayoub, Alex and Jia, Zeyu and Szepesv\'{a}ri, Csaba and Wang, Mengdi and Yang, L
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# bertsekas1996: Dynamic Programming and Optimal Control
# Authors: Bertsekas, Dimitri P.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# bhandari2021finite: A Finite Time Analysis of Temporal Difference Learning with Linear Function Appr
# Authors: Bhandari, Jalaj and Russo, Daniel and Singal, Raghav
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# boute2022: Can Deep Reinforcement Learning Improve Inventory Management? Performance on Los
# Authors: Gijsbrechts, J. and Boute, R. N. and Van Mieghem, J. A. and Zhang, D. J.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# carvalho2020convergence: A New Convergent Variant of Q-Learning with Linear Function Approximation
# Authors: Carvalho, Diogo and Melo, Francisco S. and Santos, Pedro
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# cen2022fast: Fast Global Convergence of Natural Policy Gradient Methods with Entropy Regulari
# Authors: Cen, Shicong and Cheng, Chen and Chen, Yuxin and Wei, Yuting and Chi, Yuejie
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# fan2020dqn: A Theoretical Analysis of Deep Q-Learning
# Authors: Fan, Jianqing and Wang, Zhaoran and Xie, Yuchen and Yang, Zhuoran
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# gaur2023fqi: Global Convergence of Fitted Q-Iteration with Two-layer Neural Networks
# Authors: Gaur, Arnab Kumar and Aggarwal, Gaurav and Agarwal, Alekh
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# geist2019regularized: A Theory of Regularized {M}arkov Decision Processes
# Authors: Geist, Matthieu and Scherrer, Bruno and Pietquin, Olivier
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# grill2020planning: Monte-Carlo Tree Search as Regularized Policy Optimization
# Authors: Grill, Jean-Bastien and Altch\'{e}, Florent and Tang, Yunhao and Hubert, Thomas 
[ -f "$DEST/Monte-Carlo_Tree_Search_as_Regularized_Policy_Optimization.pdf" ] || curl -sL -o "$DEST/Monte-Carlo_Tree_Search_as_Regularized_Policy_Optimization.pdf" "https://arxiv.org/pdf/2007.12509.pdf"
# Source: s2_arxiv

# grimm2020value: The Value Equivalence Principle for Model-Based Reinforcement Learning
# Authors: Grimm, Christopher and Barreto, Andr\'{e} and Singh, Satinder and Silver, David
[ -f "$DEST/The_Value_Equivalence_Principle_for_Model-Based_Reinforcemen.pdf" ] || curl -sL -o "$DEST/The_Value_Equivalence_Principle_for_Model-Based_Reinforcemen.pdf" "https://arxiv.org/pdf/2011.03506.pdf"
# Source: s2_arxiv

# grimm2021proper: Proper Value Equivalence
# Authors: Grimm, Christopher and Barreto, Andr\'{e} and Singh, Satinder
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# he2021nearly: Nearly Minimax Optimal Reinforcement Learning for Discounted {MDPs}
# Authors: He, Jiafan and Zhou, Dongruo and Gu, Quanquan
[ -f "$DEST/Nearly_Minimax_Optimal_Reinforcement_Learning_for_Discounted.pdf" ] || curl -sL -o "$DEST/Nearly_Minimax_Optimal_Reinforcement_Learning_for_Discounted.pdf" "https://arxiv.org/pdf/2010.00587.pdf"
# Source: s2_arxiv

# janner2019model: When to Trust Your Model: Model-Based Policy Optimization
# Authors: Janner, Michael and Fu, Justin and Zhang, Marvin and Levine, Sergey
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# lan2020maxmin: Maxmin Q-learning: Controlling the Estimation Bias of Q-learning
# Authors: Lan, Qingfeng and Pan, Yangchen and Fyshe, Alona and White, Martha
[ -f "$DEST/Maxmin_Q-learning_Controlling_the_Estimation_Bias_of_Q-learn.pdf" ] || curl -sL -o "$DEST/Maxmin_Q-learning_Controlling_the_Estimation_Bias_of_Q-learn.pdf" "https://arxiv.org/pdf/2002.06487.pdf"
# Source: s2_arxiv

# lee2025optimal: Optimal Non-Asymptotic Rates of Value Iteration for Average-Reward {MDPs}
# Authors: Lee, Dongmin and Ryu, Ernest K.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# li2023actorcritic: Convergence of Actor-Critic with Multi-Layer Neural Networks
# Authors: Li, Haochuan and others
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# li2024breaking: Breaking the Sample Size Barrier in Model-Based Reinforcement Learning with a Ge
# Authors: Li, Gen and Wei, Yuting and Chi, Yuejie and Gu, Yuantao and Chen, Yuxin
[ -f "$DEST/Breaking_the_Sample_Size_Barrier_in_Model-Based_Reinforcemen.pdf" ] || curl -sL -o "$DEST/Breaking_the_Sample_Size_Barrier_in_Model-Based_Reinforcemen.pdf" "https://arxiv.org/pdf/2005.12900"
# Source: semantic_scholar

# li2024minimax: Is Q-Learning Minimax Optimal? A Tight Sample Complexity Analysis
# Authors: Li, Gen and Shi, Laixi and Chen, Yuxin and Wei, Yuting and Chi, Yuejie
[ -f "$DEST/Is_Q-Learning_Minimax_Optimal_A_Tight_Sample_Complexity_Anal.pdf" ] || curl -sL -o "$DEST/Is_Q-Learning_Minimax_Optimal_A_Tight_Sample_Complexity_Anal.pdf" "https://arxiv.org/pdf/2102.06548"
# Source: semantic_scholar

# li2024offline: Settling the Sample Complexity of Model-Based Offline Reinforcement Learning
# Authors: Li, Gen and Shi, Laixi and Chen, Yuxin and Chi, Yuejie and Wei, Yuting
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# lim2024regularized: Regularized Q-Learning
# Authors: Lim, Han-Dong and Lee, Donghwan
[ -f "$DEST/Regularized_Q-Learning.pdf" ] || curl -sL -o "$DEST/Regularized_Q-Learning.pdf" "https://arxiv.org/pdf/2401.15196.pdf"
# Source: s2_arxiv

# lobel2024simulation: An Optimal Tightness Bound for the Simulation Lemma
# Authors: Lobel, Sam and Parr, Ronald
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# mao2021nonstationary: Near-Optimal Model-Free Reinforcement Learning in Non-Stationary Episodic {MDPs}
# Authors: Mao, Weichao and Zhang, Kaiqing and Zhu, Ruihao and Simchi-Levi, David and Basar
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# moerland2022unifying: A Unifying Framework for Reinforcement Learning and Planning
# Authors: Moerland, Thomas M. and Broekens, Joost and Plaat, Aske and Jonker, Catholijn M.
[ -f "$DEST/A_Unifying_Framework_for_Reinforcement_Learning_and_Planning.pdf" ] || curl -sL -o "$DEST/A_Unifying_Framework_for_Reinforcement_Learning_and_Planning.pdf" "https://arxiv.org/pdf/2006.15009.pdf"
# Source: known_arxiv

# muller2024npg: Fisher--Rao Gradient Flows of Linear Programs and State-Action Natural Policy Gr
# Authors: M\"{u}ller, Johannes and Cayci, Semih and Mont\'{u}far, Guido
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# nomura2025: Deep Reinforcement Learning for Dynamic Pricing and Ordering Policies in Perisha
# Authors: Nomura, Y. and others
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Ramaswamy2021: Analyzing Approximate Value Iteration Algorithms
# Authors: Ramaswamy, Arunselvan
[ -f "$DEST/Analyzing_Approximate_Value_Iteration_Algorithms.pdf" ] || curl -sL -o "$DEST/Analyzing_Approximate_Value_Iteration_Algorithms.pdf" "https://arxiv.org/pdf/1709.04673.pdf"
# Source: bib_arxiv

# ren2021underestimation: On the Estimation Bias in Double Q-Learning
# Authors: Ren, Zhizhou and others
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# rowland2024quantile: An Analysis of Quantile Temporal-Difference Learning
# Authors: Rowland, Mark and Dabney, Will and Munos, R\'{e}mi
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# sabri2024: Reinforcement learning and stochastic dynamic programming for jointly scheduling
# Authors: Sabri, M. and others
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# singh2000: Convergence results for single-step on-policy reinforcement-learning algorithms
# Authors: Singh, Satinder and Jaakkola, Tommi and Littman, Michael L and Szepesv{\'a}ri, C
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# sutton2018: Reinforcement Learning: An Introduction
# Authors: Sutton, Richard S. and Barto, Andrew G.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# tsitsiklis2002: On the Convergence of Optimistic Policy Iteration
# Authors: Tsitsiklis, John N.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# wang2020eluder: Reinforcement Learning with General Value Function Approximation: Provably Effic
# Authors: Wang, Ruosong and Salakhutdinov, Ruslan and Yang, Lin
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# watkins1992_paper: Q-Learning
# Authors: Watkins, Christopher J. C. H. and Dayan, Peter
# NO OPEN-ACCESS SOURCE FOUND. DOI: 10.1007/bf00992698 Download manually.

# williams1992_reinforce: Simple statistical gradient-following algorithms for connectionist reinforcement
# Authors: Williams, Ronald J.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# wu2020twotimescale: A Finite-Time Analysis of Two Time-Scale Actor-Critic Methods
# Authors: Wu, Yue and Zhang, Weitong and Xu, Pan and Gu, Quanquan
[ -f "$DEST/A_Finite-Time_Analysis_of_Two_Time-Scale_Actor-Critic_Method.pdf" ] || curl -sL -o "$DEST/A_Finite-Time_Analysis_of_Two_Time-Scale_Actor-Critic_Method.pdf" "https://arxiv.org/pdf/2005.01350.pdf"
# Source: s2_arxiv

# xiao2022convergence: On the Convergence Rates of Policy Gradient Methods
# Authors: Xiao, Lin
[ -f "$DEST/On_the_Convergence_Rates_of_Policy_Gradient_Methods.pdf" ] || curl -sL -o "$DEST/On_the_Convergence_Rates_of_Policy_Gradient_Methods.pdf" "https://arxiv.org/pdf/2201.07443.pdf"
# Source: s2_arxiv

# zhang2021target: Breaking the Deadly Triad with a Target Network
# Authors: Zhang, Shangtong and Yao, Hengshuai and Whiteson, Shimon
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Zhang2023: On the Convergence and Sample Complexity Analysis of Deep Q-Networks with $\epsi
# Authors: Zhang, Shuai and Li, Hongkang and Wang, Meng and Liu, Miao and Chen, Pin-Yu and 
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# zhang2024settling: Settling the Sample Complexity of Online Reinforcement Learning
# Authors: Zhang, Zihan and Chen, Yuxin and Lee, Jason D. and Du, Simon S.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# zhu2024representation: On Representation Complexity of Model-based and Model-free Reinforcement Learnin
# Authors: Zhu, Hanlin and Huang, Baihe and Russell, Stuart
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

