#!/usr/bin/env bash
# Download papers for ch01_history
# Auto-generated by generate_download_scripts.py

set -euo pipefail

DEST="/Users/pranjal/Code/rl/ch01_history/papers"
mkdir -p "$DEST"

# AckerbergCavesFrazer2015: Identification Properties of Recent Production Function Estimators
# Authors: Ackerberg, Daniel A. and Caves, Kevin and Frazer, Garth
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# AguirregabiriaMira2007: Sequential Estimation of Dynamic Discrete Games
# Authors: Aguirregabiria, Victor and Mira, Pedro
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# AtashbarShi2023: Solving Macroeconomic Models with Deep Reinforcement Learning
# Authors: Atashbar, Tohid and Shi, Shuping
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Auer2002: Finite-time analysis of the multiarmed bandit problem
# Authors: Auer, Peter and Cesa-Bianchi, Nicolo and Fischer, Paul
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Bai2022: Constitutional AI: Harmlessness from AI Feedback
# Authors: Bai, Yuntao and Kadavath, Saurav and Kundu, Sandipan and Askell, Amanda and Kern
[ -f "$DEST/Constitutional_AI_Harmlessness_from_AI_Feedback.pdf" ] || curl -sL -o "$DEST/Constitutional_AI_Harmlessness_from_AI_Feedback.pdf" "https://arxiv.org/pdf/2212.08073.pdf"
# Source: known_arxiv

# BajariBenkardLevin2007: Estimating Dynamic Models of Imperfect Competition
# Authors: Bajari, Patrick and Benkard, C. Lanier and Levin, Jonathan
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# BartoSuttonAnderson1983: Neuronlike adaptive elements that can solve difficult learning control problems
# Authors: Barto, Andrew G. and Sutton, Richard S. and Anderson, Charles W.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Bellman1957: Dynamic Programming
# Authors: Bellman, Richard
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# BerryLevinsohnPakes1995: Automobile Prices in Market Equilibrium
# Authors: Berry, Steven and Levinsohn, James and Pakes, Ariel
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# BertsekasTsitsiklis1996: Neuro-Dynamic Programming
# Authors: Bertsekas, Dimitri P. and Tsitsiklis, John N.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# brafman2002rmax: R-max -- A General Polynomial Time Algorithm for Near-Optimal Reinforcement Lear
# Authors: Brafman, Ronen I. and Tennenholtz, Moshe
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# CilibertoTamer2009: Market Structure and Multiple Equilibria in Airline Markets
# Authors: Ciliberto, Federico and Tamer, Elie
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# DubeFoxSu2012: Improving the Numerical Performance of Static and Dynamic Aggregate Discrete Cho
# Authors: Dubé, Jean-Pierre and Fox, Jeremy T. and Su, Che-Lin
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# FernandezVillaverdeNunoPerla2024: Solving High-Dimensional Dynamic Programming Problems Using Deep Learning
# Authors: Fernández-Villaverde, Jesús and Nuño, Galo and Perla, Jesse
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Haavelmo1944: The Probability Approach in Econometrics
# Authors: Haavelmo, Trygve
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Heckman1979: Sample Selection Bias as a Specification Error
# Authors: Heckman, James J.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# HoodKoopmans1953: Studies in Econometric Method
# Authors: Hood, William C. and Koopmans, Tjalling C.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# HotzMiller1993: Conditional Choice Probabilities and the Estimation of Dynamic Models
# Authors: Hotz, V. Joseph and Miller, Robert A.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Howard1960: Dynamic Programming and Markov Processes
# Authors: Howard, Ronald A.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Igami2020: Artificial intelligence as structural estimation: Deep Blue, Bonanza, and AlphaG
# Authors: Igami, Mitsuru
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Kakade2001: A Natural Policy Gradient
# Authors: Kakade, Sham M.
[ -f "$DEST/A_Natural_Policy_Gradient.pdf" ] || curl -sL -o "$DEST/A_Natural_Policy_Gradient.pdf" "https://arxiv.org/pdf/cs/0106005.pdf"
# Source: known_arxiv

# MaliarMaliarWinant2021: Deep Learning for Solving Dynamic Economic Models
# Authors: Maliar, Lilia and Maliar, Serguei and Winant, Pablo
[ -f "$DEST/Deep_Learning_for_Solving_Dynamic_Economic_Models.pdf" ] || curl -sL -o "$DEST/Deep_Learning_for_Solving_Dynamic_Economic_Models.pdf" "https://arxiv.org/pdf/2004.05668.pdf"
# Source: known_arxiv

# McFadden1974: Conditional Logit Analysis of Qualitative Choice Behavior
# Authors: McFadden, Daniel
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Miller1984: Job Matching and Occupational Choice
# Authors: Miller, Robert A.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Minsky1954: Neural Nets and the Brain Model Problem
# Authors: Minsky, Marvin
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Mnih2015: Human-level control through deep reinforcement learning
# Authors: Mnih, Volodymyr and Kavukcuoglu, Koray and Silver, David and Rusu, Andrei A. and
[ -f "$DEST/Human-level_control_through_deep_reinforcement_learning.pdf" ] || curl -sL -o "$DEST/Human-level_control_through_deep_reinforcement_learning.pdf" "https://arxiv.org/pdf/1312.5602.pdf"
# Source: known_arxiv

# NgRussell2000: Algorithms for Inverse Reinforcement Learning
# Authors: Ng, Andrew Y. and Russell, Stuart J.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Ouyang2022: Training language models to follow instructions with human feedback
# Authors: Ouyang, Long and Wu, Jeff and Jiang, Xu and Almeida, Diogo and Wainwright, Carro
[ -f "$DEST/Training_language_models_to_follow_instructions_with_human_f.pdf" ] || curl -sL -o "$DEST/Training_language_models_to_follow_instructions_with_human_f.pdf" "https://arxiv.org/pdf/2203.02155.pdf"
# Source: known_arxiv

# PesendorferSchmidtDengler2008: Asymptotic Least Squares Estimators for Dynamic Games
# Authors: Pesendorfer, Martin and Schmidt-Dengler, Philipp
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Petrin2002: Quantifying the Benefits of New Products: The Case of the Minivan
# Authors: Petrin, Amil
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Rust1987: Optimal Replacement of GMC Bus Engines: An Empirical Model of Harold Zurcher
# Authors: Rust, John
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Samuel1959: Some Studies in Machine Learning Using the Game of Checkers
# Authors: Samuel, Arthur L.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Schulman2015: Trust Region Policy Optimization
# Authors: Schulman, John and Levine, Sergey and Abbeel, Pieter and Jordan, Michael and Mor
[ -f "$DEST/Trust_Region_Policy_Optimization.pdf" ] || curl -sL -o "$DEST/Trust_Region_Policy_Optimization.pdf" "https://arxiv.org/pdf/1502.05477.pdf"
# Source: known_arxiv

# Schulman2017: Proximal Policy Optimization Algorithms
# Authors: Schulman, John and Wolski, Filip and Dhariwal, Prafulla and Radford, Alec and Kl
[ -f "$DEST/Proximal_Policy_Optimization_Algorithms.pdf" ] || curl -sL -o "$DEST/Proximal_Policy_Optimization_Algorithms.pdf" "https://arxiv.org/pdf/1707.06347.pdf"
# Source: known_arxiv

# Shannon1950: Programming a Computer for Playing Chess
# Authors: Shannon, Claude E.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Silver2016: Mastering the game of Go with deep neural networks and tree search
# Authors: Silver, David and Huang, Aja and Maddison, Chris J. and Guez, Arthur and Sifre, 
[ -f "$DEST/Mastering_the_game_of_Go_with_deep_neural_networks_and_tree.pdf" ] || curl -sL -o "$DEST/Mastering_the_game_of_Go_with_deep_neural_networks_and_tree.pdf" "https://arxiv.org/pdf/1607.01491.pdf"
# Source: known_arxiv

# Silver2017: Mastering the Game of Go without Human Knowledge
# Authors: Silver, David and Schrittwieser, Julian and Simonyan, Karen and Antonoglou, Ioan
[ -f "$DEST/Mastering_the_Game_of_Go_without_Human_Knowledge.pdf" ] || curl -sL -o "$DEST/Mastering_the_Game_of_Go_without_Human_Knowledge.pdf" "https://arxiv.org/pdf/1706.01427.pdf"
# Source: known_arxiv

# Sutton1988: Learning to Predict by the Methods of Temporal Differences
# Authors: Richard S. Sutton
# NO OPEN-ACCESS SOURCE FOUND. DOI: 10.1023/A:1022633531479 Download manually.

# Sutton1990: Integrated architectures for learning, planning, and reacting based on approxima
# Authors: Sutton, Richard S.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Sutton1999Options: Between MDPs and semi-MDPs: A framework for temporal abstraction in reinforcemen
# Authors: Sutton, Richard S. and Precup, Doina and Singh, Satinder
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# SuttonBarto1998: Reinforcement Learning: An Introduction
# Authors: Sutton, Richard S. and Barto, Andrew G.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Tesauro1994: TD-Gammon, a self-teaching backgammon program, achieves master-level play
# Authors: Tesauro, Gerald
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# watkins1992_paper: Q-Learning
# Authors: Watkins, Christopher J. C. H. and Dayan, Peter
# NO OPEN-ACCESS SOURCE FOUND. DOI: 10.1007/bf00992698 Download manually.

# WeintraubBenkardVanRoy2008: Markov Perfect Industry Dynamics with Many Firms
# Authors: Weintraub, Gabriel Y. and Benkard, C. Lanier and Van Roy, Benjamin
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Williams1992: Simple statistical gradient-following algorithms for connectionist reinforcement
# Authors: Williams, Ronald J.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Wolpin1984: An Estimable Dynamic Stochastic Model of Fertility and Child Mortality
# Authors: Wolpin, Kenneth I.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

