#!/usr/bin/env bash
# Download papers for ch06_bandits
# Auto-generated by generate_download_scripts.py

set -euo pipefail

DEST="/Users/pranjal/Code/rl/ch06_bandits/papers"
mkdir -p "$DEST"

# Akcay2022: Online Learning Algorithms for Auction Reserve Price Optimization with Censored 
# Authors: Akcay, Alp and Atan, Onur and Sayin, Muhammed O. and Eryilmaz, Atilla
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Badanidiyuru2013: Bandits with Knapsacks
# Authors: Badanidiyuru, Ashwinkumar and Kleinberg, Robert and Slivkins, Aleksandrs
[ -f "$DEST/Bandits_with_Knapsacks.pdf" ] || curl -sL -o "$DEST/Bandits_with_Knapsacks.pdf" "https://arxiv.org/pdf/1305.2545.pdf"
# Source: known_arxiv

# BennettKallus2023: Proximal Reinforcement Learning: A Bridge Between Causal Inference and Sequentia
# Authors: Bennett, Daniel T. and Kallus, Nathan
[ -f "$DEST/Proximal_Reinforcement_Learning_A_Bridge_Between_Causal_Infe.pdf" ] || curl -sL -o "$DEST/Proximal_Reinforcement_Learning_A_Bridge_Between_Causal_Infe.pdf" "https://arxiv.org/pdf/2306.12351.pdf"
# Source: bib_arxiv

# CesaBianchi2015: Regret Minimization for Reserve Prices in Second-Price Auctions
# Authors: Cesa-Bianchi, Nicolo and Gentile, Claudio and Mansour, Yishay
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Flajolet2017: Real-Time Bidding with Side Information
# Authors: Flajolet, Arthur and Jaillet, Patrick
[ -f "$DEST/Real-Time_Bidding_with_Side_Information.pdf" ] || curl -sL -o "$DEST/Real-Time_Bidding_with_Side_Information.pdf" "https://arxiv.org/pdf/1712.09966.pdf"
# Source: known_arxiv

# Goyal2022: Online Learning for Multi-product Dynamic Pricing with Multinomial Logit Choice 
# Authors: Goyal, Vikas and Jain, Negin and Slivkins, Aleksandrs
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Guo2023: Multi-Agent Reinforcement Learning in Dynamic Pricing Games
# Authors: Guo, Yanjun and Kanoria, Yash and Simchi-Levi, David
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# liao2024: Offline Reinforcement Learning with Instrumental Variables in Confounded Markov 
# Authors: Liao, Ziyan and An, Ziqi and Wu, Xiaoxiao and Liu, Yang and Yin, Min
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Misra2019: Dynamic Online Pricing with Incomplete Information Using Multiarmed Bandit Exper
# Authors: Misra, Kanishka and Schwartz, Eric M. and Abernethy, Jacob
[ -f "$DEST/Dynamic_Online_Pricing_with_Incomplete_Information_Using_Mul.pdf" ] || curl -sL -o "$DEST/Dynamic_Online_Pricing_with_Incomplete_Information_Using_Mul.pdf" "https://arxiv.org/pdf/1902.04229.pdf"
# Source: known_arxiv

# Mueller2019: Low-Rank Bandit Methods for High-Dimensional Dynamic Pricing
# Authors: Mueller, Jonas and Syrgkanis, Vasilis and Taddy, Matt
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Nuara2018: A Combinatorial-Bandit Algorithm for the Online Joint Bid/Budget Optimization of
# Authors: Nuara, Alessandro and Trovo, Francesco and Gatti, Nicola and Restelli, Marcello
[ -f "$DEST/A_Combinatorial-Bandit_Algorithm_for_the_Online_Joint_BidBud.pdf" ] || curl -sL -o "$DEST/A_Combinatorial-Bandit_Algorithm_for_the_Online_Joint_BidBud.pdf" "https://arxiv.org/pdf/1811.09476.pdf"
# Source: known_arxiv

# Sankararaman2018: Combinatorial Semi-Bandits with Knapsacks
# Authors: Sankararaman, Karthik Abinav and Slivkins, Aleksandrs
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# WangQiShi2023: Super-RL: A general framework for offline reinforcement learning by leveraging s
# Authors: Wang, Yanchao and Qi, Gaoyue and Shi, Chen
[ -f "$DEST/Super-RL_A_general_framework_for_offline_reinforcement_learn.pdf" ] || curl -sL -o "$DEST/Super-RL_A_general_framework_for_offline_reinforcement_learn.pdf" "https://arxiv.org/pdf/2310.09941.pdf"
# Source: bib_arxiv

# Xu2021: Logarithmic Regret in Feature-based Dynamic Pricing
# Authors: Xu, Yining and Wang, Zhe and Yu, Yuchen
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

