#!/usr/bin/env bash
# Download papers for ch03_rl_structural_est
# Auto-generated by generate_download_scripts.py

set -euo pipefail

DEST="/Users/pranjal/Code/rl/ch03_rl_structural_est/papers"
mkdir -p "$DEST"

# AdusumilliEckardt2022: Estimation of Dynamic Discrete Choice Models with Differentiable Temporal-Differ
# Authors: Adusumilli, S. and Eckardt, M. and Tate, G.
[ -f "$DEST/Estimation_of_Dynamic_Discrete_Choice_Models_with_Differenti.pdf" ] || curl -sL -o "$DEST/Estimation_of_Dynamic_Discrete_Choice_Models_with_Differenti.pdf" "https://arxiv.org/pdf/2209.15174.pdf"
# Source: bib_arxiv

# AskerEtAl2020: A computational framework for analyzing dynamic auctions: The market impact of i
# Authors: Asker, John and Fershtman, Chaim and Jeon, Jihye and Pakes, Ariel
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# AtashbarShi2023: Solving Macroeconomic Models with Deep Reinforcement Learning
# Authors: Atashbar, Tohid and Shi, Shuping
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# BreroEtAl2021: Reinforcement Learning of Sequential Price Mechanisms
# Authors: Brero, Gianluca and Eden, Alon and Gerstgrasser, Matthias and Parkes, David C. a
[ -f "$DEST/Reinforcement_Learning_of_Sequential_Price_Mechanisms.pdf" ] || curl -sL -o "$DEST/Reinforcement_Learning_of_Sequential_Price_Mechanisms.pdf" "https://arxiv.org/pdf/2101.07824.pdf"
# Source: known_arxiv

# Covarrubias2022: Collusion with Deep Reinforcement Learning
# Authors: Covarrubias, Bryan S. and Zentefis, Alexander and Abiseid, Jose M.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# curry2022: Finding Equilibrium in Heterogeneous Agent Models with Deep Reinforcement Learni
# Authors: Curry, Michael D. and Banerjee, Carsenate and Li, Yan and Evans, Paul and Svitov
[ -f "$DEST/Finding_Equilibrium_in_Heterogeneous_Agent_Models_with_Deep.pdf" ] || curl -sL -o "$DEST/Finding_Equilibrium_in_Heterogeneous_Agent_Models_with_Deep.pdf" "https://arxiv.org/pdf/2205.07165.pdf"
# Source: known_arxiv

# FershtmanPakes2012: Dynamic games with asymmetric information: A framework for empirical work
# Authors: Fershtman, Chaim and Pakes, Ariel
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# GrafEtAl2024: Deep Reinforcement Learning for Auctions: Evaluating Bidding Strategies Effectiv
# Authors: Graf, Lukas and Hummel, Patrick and Bichler, Martin
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# HinterlangTaenzer2024: Optimal Monetary Policy using Reinforcement Learning
# Authors: Hinterlang, Natascha and Taenzer, Tobias
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Hollenbeck2019: Horizontal Mergers and Innovation in Concentrated Industries
# Authors: Hollenbeck, Brett
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# HuYang2025: Structural Estimation with Policy Gradient Methods
# Authors: Hu, Yingyao and Yang, Zhangyi
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# LomysMagnolfi2024: Estimation of Games under No Regret: Structural Econometrics for AI
# Authors: Lomys, Nikolay and Magnolfi, Luca
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# RavindranathEtAl2024: Deep Reinforcement Learning for Sequential Combinatorial Auctions
# Authors: Ravindranath, Sai Srivatsa and Feng, Zhe and Wang, Di and Zaheer, Manzil and Meh
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

