#!/usr/bin/env bash
# Download papers for ch05_rl_in_games
# Auto-generated by generate_download_scripts.py

set -euo pipefail

DEST="/Users/pranjal/Code/rl/ch05_rl_in_games/papers"
mkdir -p "$DEST"

# borgers1997learning: Learning through reinforcement and replicator dynamics
# Authors: B{\"o}rgers, Tilman and Sarin, Rajiv
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# BowlingVeloso2002: Multiagent Learning Using a Variable Learning Rate
# Authors: Bowling, Michael and Veloso, Manuela
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Brown1951: Iterative solution of games by fictitious play
# Authors: Brown, George W.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Brown2019: Deep Counterfactual Regret Minimization
# Authors: Brown, Noam and Lerer, Adam and Gross, Sam and Sandholm,Tuomas
[ -f "$DEST/Deep_Counterfactual_Regret_Minimization.pdf" ] || curl -sL -o "$DEST/Deep_Counterfactual_Regret_Minimization.pdf" "https://arxiv.org/pdf/1811.00164.pdf"
# Source: known_arxiv

# brown2019_deepcfr: Deep Counterfactual Regret Minimization
# Authors: Brown, Noam and Lerer, Adam and Gross, Sam and Sandholm,Tuomas
[ -f "$DEST/Deep_Counterfactual_Regret_Minimization.pdf" ] || curl -sL -o "$DEST/Deep_Counterfactual_Regret_Minimization.pdf" "https://arxiv.org/pdf/1811.00164.pdf"
# Source: known_arxiv

# Cross1973: A stochastic learning model of economic behavior
# Authors: Cross, John G.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Daskalakis2009: The Complexity of Computing a Nash Equilibrium
# Authors: Daskalakis, Constantinos and Goldberg, Paul W. and Papadimitriou, Christos H.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# deepmind2022: Mastering the game of Stratego with model-free multiagent reinforcement learning
# Authors: Perolat, Jean and Munos, Remi and Lespiau, Jean-Baptiste and Lauriere, Mathis an
[ -f "$DEST/Mastering_the_game_of_Stratego_with_model-free_multiagent_re.pdf" ] || curl -sL -o "$DEST/Mastering_the_game_of_Stratego_with_model-free_multiagent_re.pdf" "https://arxiv.org/pdf/2206.15378.pdf"
# Source: known_arxiv

# HeinrichSilver2016: Neural fictitious self-play
# Authors: Heinrich, Johannes and Silver, David
[ -f "$DEST/Neural_fictitious_self-play.pdf" ] || curl -sL -o "$DEST/Neural_fictitious_self-play.pdf" "https://arxiv.org/pdf/1603.01121.pdf"
# Source: known_arxiv

# hu2003_nashq: Nash Q-learning for general-sum stochastic games
# Authors: Hu, Junling and Wellman, Michael P
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Letcher2019: Differentiable Game Mechanics
# Authors: Letcher, Antony and Balduzzi, David and Gemp, Ian and Foerster, Jakob N and Czar
[ -f "$DEST/Differentiable_Game_Mechanics.pdf" ] || curl -sL -o "$DEST/Differentiable_Game_Mechanics.pdf" "https://arxiv.org/pdf/1905.04926.pdf"
# Source: known_arxiv

# littman1994_minimaxq: Markov games as a framework for multi-agent reinforcement learning
# Authors: Littman, Michael L
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Mazumdar2019: On gradient-based learning in continuous games
# Authors: Mazumdar, Eric and others
[ -f "$DEST/On_gradient-based_learning_in_continuous_games.pdf" ] || curl -sL -o "$DEST/On_gradient-based_learning_in_continuous_games.pdf" "https://arxiv.org/pdf/1906.01217.pdf"
# Source: known_arxiv

# MondererShapley1996: Potential games
# Authors: Monderer, Dov and Shapley, Lloyd S.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# moravcik2017: DeepStack: Expert-level artificial intelligence in no-limit poker
[ -f "$DEST/DeepStack_Expert-level_artificial_intelligence_in_no-limit_p.pdf" ] || curl -sL -o "$DEST/DeepStack_Expert-level_artificial_intelligence_in_no-limit_p.pdf" "https://arxiv.org/pdf/1701.01724.pdf"
# Source: known_arxiv

# Robinson1951: An iterative method of solving a game
# Authors: Robinson, Julia
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Shapley1964: Some topics in two-person games
# Authors: Shapley, Lloyd S.
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# singh2000: Convergence results for single-step on-policy reinforcement-learning algorithms
# Authors: Singh, Satinder and Jaakkola, Tommi and Littman, Michael L and Szepesv{\'a}ri, C
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Sutton1999: Policy Gradient Methods for Reinforcement Learning with Function Approximation
# Authors: Sutton, Richard S. and McAllester, David A. and Singh, Satinder P. and Mansour, 
[ -f "$DEST/Policy_Gradient_Methods_for_Reinforcement_Learning_with_Func.pdf" ] || curl -sL -o "$DEST/Policy_Gradient_Methods_for_Reinforcement_Learning_with_Func.pdf" "https://arxiv.org/pdf/cs/9905014.pdf"
# Source: known_arxiv

# Tan1993: Multi-agent reinforcement learning: Independent versus cooperative agents
# Authors: Tan, Ming
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# Tuyls2003: An evolutionary game theoretic approach to Q-learning in multi-agent systems
# Authors: Tuyls, Karl and Nowé, Ann and Manderick, Bernard and Verbeeck, Katja
# NO OPEN-ACCESS SOURCE FOUND. Download manually.

# zinkevich2008: Regret minimization in games with incomplete information
# Authors: Zinkevich, Martin and Johanson, Michael and Bowling, Michael and Piccione, Carme
[ -f "$DEST/Regret_minimization_in_games_with_incomplete_information.pdf" ] || curl -sL -o "$DEST/Regret_minimization_in_games_with_incomplete_information.pdf" "https://arxiv.org/pdf/1811.00164.pdf"
# Source: known_arxiv

